-- MySQL Script generated by MySQL Workbench
-- Sun Mar 29 14:07:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mtamar06
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mtamar06
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mtamar06` DEFAULT CHARACTER SET utf8 ;
USE `mtamar06` ;

-- -----------------------------------------------------
-- Table `mtamar06`.`concerto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mtamar06`.`concerto` (
  `idconcerto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_evento` VARCHAR(255) NOT NULL,
  `nome_concerto` VARCHAR(255) NOT NULL,
  `data` VARCHAR(255) NOT NULL,
  `endereco` TEXT NOT NULL,
  `link_endereco` TEXT NOT NULL,
  PRIMARY KEY (`idconcerto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mtamar06`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mtamar06`.`photo` (
  `id_photo` INT(11) NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(255) NOT NULL,
  `upload_time` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_photo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mtamar06`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mtamar06`.`user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(255) NOT NULL,
  `email_user` VARCHAR(255) NOT NULL,
  `photo_permission` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `video_permission` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `concert_permission` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mtamar06`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mtamar06`.`video` (
  `id_video` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `link_youtube` TEXT NOT NULL,
  `categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_video`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mtamar06`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mtamar06`.`email` (
  `idemail` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idemail`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
